PortalVentas/config/routes.rb
Rails.application.routes.draw do
  
  #Pagina principal
  root 'features#index'

  #Session
  resources :sessions, only: [:new, :create, :destroy]
  
  #Categoria
  resources :categories

  #Ruta del Usuario
  resources :users 

  #Rutas para los comentarios por articulo
  resources :features do
    resources :comments
    resources :notifications
    member do
      get 'like'
    end
  end
  
  #Admin
  get 'admin/index'

  #Rutas del login
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  #Update articulo
  get '/admin/acceptFeature/:id' => 'admin#acceptFeature', :as =>'acceptFeature'
  #Update tipo de Usuario
  get '/admin/updateUserType/:id' => 'admin#updateUserType', :as =>'updateUserType'
   #Update category
  get '/admin/acceptCategory/:id' => 'admin#acceptCategory', :as =>'acceptCategory'
  #Betar commrnt
  get '/feature/changeCommentState/:id' => 'features#changeCommentState', :as =>'changeCommentState'
end

PortalVentas/app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :feature
	belongs_to :user
end

PortalVentas/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
    @notification.feature = Feature.find(params[:feature_id])
    @path = { url: feature_notifications_path(@notification.feature), html: { method: :post } }

  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)
    @notification.notificationDate = Time.now
    @notification.feature = Feature.find(params[:feature_id])
    @notification.user = @notification.feature.user
    @notification.feature.update(publicationState: 'Rechazado')
    respond_to do |format|
      if @notification.save
        format.html { redirect_to admin_index_path(current_user) }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:notification, :notificationDate, :feature_id, :user_id)
    end
end

PortalVentas/app/helpers/notifications_helper.rb
module NotificationsHelper
end

PortalVentas/app/views/notifications/_form.html.haml
= form_for @notification, @path do |f|
  - if @notification.errors.any?
    #error_explanation
      %h2= "#{pluralize(@notification.errors.count, "error")} prohibited this notification from being saved:"
      %ul
        - @notification.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :notification
    %br
    = f.text_area :notification,:class=>'notification'

  .actions
    = f.submit 'Save', :class=>'button'

PortalVentas/app/views/notifications/edit.html.haml
%h1 Editing notification

= render 'form'

= link_to 'Show', @notification
\|
= link_to 'Back', notifications_path

PortalVentas/app/views/notifications/index.html.haml
%h1 Listing notifications

%table
  %thead
    %tr
      %th Reason
      %th Notificationdate
      %th
      %th
      %th

  %tbody
    - @notifications.each do |notification|
      %tr
        %td= notification.reason
        %td= notification.notificationDate
        %td= link_to 'Show', notification
        %td= link_to 'Edit', edit_notification_path(notification)
        %td= link_to 'Destroy', notification, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Notification', new_notification_path

= link_to 'Back', admin_index_path

PortalVentas/app/views/notifications/new.html.haml
%h1 New notification: #{@notification.feature.user.userName}
.divEditar
	= render 'form'

= link_to 'Back', admin_index_path(current_user), :class => 'buttonBack'

PortalVentas/app/views/notifications/show.html.haml
%p#notice= notice

%p
  %b Reason:
  = @notification.reason
%p
  %b Notificationdate:
  = @notification.notificationDate

= link_to 'Edit', edit_notification_path(@notification)
\|
= link_to 'Back', notifications_path