PortalVentas/config/routes.rb
Rails.application.routes.draw do
  
  #Pagina principal
  root 'features#index'

  #Session
  resources :sessions, only: [:new, :create, :destroy]
  
  #Categoria
  resources :categories

  #Ruta del Usuario
  resources :users 

  #Rutas para los comentarios por articulo
  resources :features do
    resources :comments
    resources :notifications
    member do
      get 'like'
    end
  end
  
  #Admin
  get 'admin/index'

  #Rutas del login
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  #Update articulo
  get '/admin/acceptFeature/:id' => 'admin#acceptFeature', :as =>'acceptFeature'
  #Update tipo de Usuario
  get '/admin/updateUserType/:id' => 'admin#updateUserType', :as =>'updateUserType'
   #Update category
  get '/admin/acceptCategory/:id' => 'admin#acceptCategory', :as =>'acceptCategory'
  #Betar commrnt
  get '/feature/changeCommentState/:id' => 'features#changeCommentState', :as =>'changeCommentState'
end

PortalVentas/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

##El usuario antes de ser guardado debe de cumplir con estos requisitos
  validates :userName, uniqueness: true
  validates :email, uniqueness: true
            #format: {
             # with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            #}
  validates :phone, uniqueness: true
  
  #Asociaciones
  has_many :features
  has_many :comments
  has_many :notifications

  #like para el articulo
  make_flagger

  #REgistra el usuario de facebook por si no esta creado
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider 
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.lastName = auth.info.last_name
      user.email    = auth.info.email
      user.userName = auth.info.username
      user.userType = 'Usuario'
      user.password = auth.info.name
      user.save!
    end
  end
end

PortalVentas/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    ##Muestro el usuario, recupero los articulos que han sido publicados por el usuario y aprobados
    @user = User.find(params[:id])
    @features = Feature.where( user_id: @user, publicationState: 'Aprobado')
    @featuresR = Feature.where( user_id: @user, publicationState: 'Rechazado')
    @notification = Notification.where( user_id: @user)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        #session[:user_id] = @user.id
        if @user.id == 1
          @user.update(userType: 'Administrador')
        else
        #Se le asigna el tipo de Usuario por defecto
          @user.update(userType: 'Usuario')
        end
        format.html { redirect_to features_path }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :lastName, :userName, :email, :phone, :userType, :password, :password_confirmation)
    end
end

PortalVentas/app/helpers/users_helper.rb
module UsersHelper
end

PortalVentas/app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :lastName
    = f.text_field :lastName
  .field
    = f.label :userName
    = f.text_field :userName
  .field
    = f.label :email
    = f.email_field :email
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :userType
    = f.text_field :userType
  .field
    = f.label :password
    = f.password_field :password
  .actions
    = f.submit 'Save'

PortalVentas/app/views/users/edit.html.haml
%h2 Editing user
.divEditar
  = form_for @user do |f|
    - if @user.errors.any?
      #error_explanation
        %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :lastName
      = f.text_field :lastName
    .field
      = f.label :userName
      = f.text_field :userName
    .field
      = f.label :email
      = f.text_field :email
    .field
      = f.label :phone
      = f.text_field :phone
    .actions
      = f.submit('Save', :class =>"buttonSave")

= link_to 'Back', @user

PortalVentas/app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Lastname
      %th Username
      %th Email
      %th Phone
      %th Usertype
      %th Password
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.lastName
        %td= user.userName
        %td= user.email
        %td= user.phone
        %td= user.userType
        %td= user.password
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

PortalVentas/app/views/users/new.html.haml
%h2 Sign Up
.divSignUp
  = form_for @user do |f|
    - if @user.errors.any?
      #error_explanation
        %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.label :name
      %br
      = f.text_field :name, :required => true
    .field
      = f.label :lastName
      %br
      = f.text_field :lastName, :required => true
    .field
      = f.label :userName
      %br
      = f.text_field :userName, :required => true
    .field
      = f.label :email
      %br
      = f.email_field :email, :required => true
    .field
      = f.label :phone
      %br
      = f.text_field :phone, :required => true
    .field
      = f.label :password
      %br
      = f.password_field :password, :required => true
    .actions
      = f.submit 'Save', :class => 'button'

= link_to 'Back', root_path, :class=> 'buttonBack'

PortalVentas/app/views/users/show.html.haml
%p#notice= notice
%br
%h5 Profile Information

%table{:class=> "tableInfo"}
  %thead
    %tr
      %td Name
      %td Lastname
      %td Username
      %td Email
      %td Phone
      %td Actions
  %tbody
    %tr
      %th= @user.name
      %th= @user.lastName
      %th= @user.userName
      %th= @user.email
      %th= @user.phone
      %th= link_to 'Edit', edit_user_path(@user),:class => "buttonEdit"
%br
%br
%br
%h5 My published products
%table{:class=> "table"}
  %thead
    %tr
      %td Tittle
      %td Price
      %td Publication_Date
      %td Category
      %td Update
      %td Delete
  %tbody
  - @features.each do |feature|
    %tr
      %th= feature.tittle
      %th= feature.price
      %th= (feature.publicationDate).strftime('%m / %d / %Y')
      %th= feature.category.name
      %th= link_to 'Edit', edit_feature_path(feature), :class => "buttonEdit"
      %th= link_to 'Delete', feature, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "buttonEdit"
  %thead
    %td{:colspan => "6"}= link_to 'Add new product', new_feature_path, :class => "differentTD"
%br
%br
%br
%h5 My rejected products

%table{:class=> "table"}
  %thead
    %tr
      %td Tittle
      %td Price
      %td Publication Date
      %td Category
      %td Reason
      %td Update
      %td Delete
  %tbody
  - @featuresR.each do |feature|
    %tr
      %th= feature.tittle
      %th= feature.price
      %th= (feature.publicationDate).strftime('%m / %d / %Y')
      %th= feature.category.name
      %th= @notification.where(feature_id: feature.id).order('id DESC').first.notification
      %th= link_to 'Edit', edit_feature_path(feature), :class => "buttonEdit"
      %th= link_to 'Destroy', feature, :method => :delete, :data => { :confirm => 'Are you sure?' } ,:class => "buttonEdit"

%br